# Generated by Django 6.0.1 on 2026-01-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_balance_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='Wallet',
        ),
    ]
