# Generated by Django 6.0.1 on 2026-02-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
