# Generated by Django 6.0.1 on 2026-01-11 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='availability',
            field=models.CharField(choices=[('Public', 'Public'), ('Anyone', 'Anyone')], default='Public', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('pet', 'user')},
        ),
    ]
