# Generated by Django 6.0.1 on 2026-01-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_availability_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='availability',
            field=models.CharField(choices=[('Public', 'Public'), ('Anyone', 'Anyone')], default='Public', max_length=20),
        ),
    ]
