# Generated by Django 6.0.1 on 2026-01-12 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_age_alter_review_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pets.pet'),
        ),
    ]
