# Generated by Django 6.0.1 on 2026-01-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_petimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
