# Generated by Django 6.0.1 on 2026-02-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='availability',
        ),
    ]
