# Generated by Django 6.0.1 on 2026-01-11 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('pets', '0003_alter_pet_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopt',
            name='pets',
        ),
        migrations.AlterField(
            model_name='adopt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adoptpet',
            name='adopt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptpets', to='order.adopt'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptpet',
            unique_together={('adopt', 'pet')},
        ),
    ]
