# Generated by Django 6.0.1 on 2026-01-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_adopt_pets_alter_adopt_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adoptpet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='adopt',
            name='status',
        ),
        migrations.AlterField(
            model_name='adopt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
