# Generated by Django 6.0.1 on 2026-02-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Pending'), ('Ready To Ship', 'Ready To Ship'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Not Paid', max_length=20),
        ),
    ]
