# Generated by Django 6.0.1 on 2026-02-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_adopt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Pending'), ('Ready To Adopt', 'Ready To Adopt'), ('Shipped', 'Shipped'), ('Adopted', 'Adopted'), ('Canceled', 'Canceled')], default='Not Paid', max_length=20),
        ),
    ]
