# Generated by Django 6.0.1 on 2026-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_adopt_updated_at_alter_adopt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='adopt',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='adopt',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Pending'), ('Ready To Adopt', 'Ready To Adopt'), ('Processing', 'Processing'), ('Adopted', 'Adopted'), ('Canceled', 'Canceled')], default='Not Paid', max_length=20),
        ),
    ]
