# Generated by Django 6.0.1 on 2026-03-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_adopt_address_adopt_name_adopt_phone_number_and_more'),
        ('pets', '0008_remove_pet_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Pending'), ('Paid', 'Paid'), ('Ready To Adopt', 'Ready To Adopt'), ('Adopted', 'Adopted'), ('Canceled', 'Canceled')], default='Not Paid', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='adoptpet',
            unique_together={('adopt', 'pet')},
        ),
    ]
